CREATE TABLE IF NOT EXISTS sasapay_webhooks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    trans_id VARCHAR(100) DEFAULT NULL,
    transaction_code VARCHAR(100) DEFAULT NULL,
    checkout_request_id VARCHAR(100) DEFAULT NULL,
    merchant_request_id VARCHAR(100) DEFAULT NULL,
    payment_request_id VARCHAR(100) DEFAULT NULL,
    result_code VARCHAR(10) DEFAULT NULL,
    result_desc TEXT DEFAULT NULL,
    source_channel VARCHAR(50) DEFAULT NULL,
    paid TINYINT(1) DEFAULT 0,
    trans_amount VARCHAR(20) DEFAULT NULL,
    bill_ref VARCHAR(100) DEFAULT NULL,
    transaction_date VARCHAR(50) DEFAULT NULL,
    customer_mobile VARCHAR(20) DEFAULT NULL,
    third_party_trans_id VARCHAR(100) DEFAULT NULL,
    first_name VARCHAR(100) DEFAULT NULL,
    middle_name VARCHAR(100) DEFAULT NULL,
    last_name VARCHAR(100) DEFAULT NULL,
    msisdn VARCHAR(20) DEFAULT NULL,
    trans_time VARCHAR(50) DEFAULT NULL,
    business_short_code VARCHAR(50) DEFAULT NULL,
    raw_body LONGTEXT DEFAULT NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_checkout_request_id (checkout_request_id),
    INDEX idx_trans_id (trans_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
